name: Generate Manifest File

on:
  push:
    branches: ["binary-only"]

jobs:
  manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Extract branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        
      - name: Generate Manifest File
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python generate.py $BRANCH_NAME

      - name: Commit and push if it's not up-to-date
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add manifests.json
          git commit -m "Update manifests.json" -a || echo "No changes to commit"
          git push
